Guia_Tlf
map<string, list<string> > Guia_Tlf::datos
list<string>& Guia_Tlf::operator[](const string &nombre)
Acceso a un elemento.
nombre nombre del elemento elemento acceder devuelve el valor asociado a un nombre, es decir el teléfono
list<string> Guia_Tlf::gettelefono(const string &nombre)
pair<map<string, list<string> >::iterator,bool> Guia_Tlf::insert(string nombre, string tlf)
Insert un nuevo telefono.
nombre nombre clave del nuevo telefono tlf numero de telefono : un pair donde first apunta al nuevo elemento insertado y bool es true si se ha insertado el nuevo tlf o o false en caso contrario
Referenced by operator+, operator^, previos.
pair<map<string, list<string> >::iterator,bool> Guia_Tlf::insert(pair< string, list< string > > p)
Insert un nuevo telefono.
p pair con el nombre y el telefono asociado : un pair donde first apunta al nuevo elemento insertado y bool es true si se ha insertado el nuevo tlf o o false en caso contrario
pair<map<string, list<string> >::iterator,bool> Guia_Tlf::insert(pair< string, string > p)
Insert un nuevo telefono.
p pair con el nombre y el telefono asociado : un pair donde first apunta al nuevo elemento insertado y bool es true si se ha insertado el nuevo tlf o o false en caso contrario
void Guia_Tlf::borrar(const string &nombre)
Borrar un telefono.
nombre nombre que se quiere borrar : en caso de que fuese un multimap borraria todos con ese nombre
Referenced by operator-.
void Guia_Tlf::borrar(const string &nombre, const string &tlf)
Borrar un telefono.
nombre nombre que se quiere borrar y telefono asociado : esta funcion nos permite borrar solamente aquel que coincida en nombre y tlf
int Guia_Tlf::size() const
Numero de telefonos.
el numero de telefonos asociados
unsigned int Guia_Tlf::contabiliza(const string &nombre)
Contabiliza cuantos telefonos tenemos asociados a un nombre.
nombre nombre sobre el que queremos consultar numero de telefonos asociados a un nombre
void Guia_Tlf::clear()
Limpia la guia.
Guia_Tlf Guia_Tlf::operator+(const Guia_Tlf &g)
Union de guias de telefonos.
g guia que se une : una nueva guia resultado de unir el objeto al que apunta this y g
References insert.
Guia_Tlf Guia_Tlf::operator-(const Guia_Tlf &g)
Diferencia de guias de telefonos.
g guia a restar : una nueva guia resultado de la diferencia del objeto al que apunta this y g
References borrar.
Guia_Tlf Guia_Tlf::operator^(const Guia_Tlf &g)
Intersección de guías de teléfonos.
g guia a restar : una nueva guia resultado de la intersección del objeto al que apunta this y g
References insert.
Guia_Tlf Guia_Tlf::previos(const string &nombre)
Obtiene una guia con los nombre previos a uno dado.
nombre nombre delimitador nueva guia sin nombres mayores que nombre
References insert.
iterator Guia_Tlf::begin()
Inicializa un iterator al comienzo de la guia.
iterator Guia_Tlf::end()
Inicializa un iterator al final de la guia.
const_iterator Guia_Tlf::begin() const
Inicializa un iterator al comienzo de la guia.
const_iterator Guia_Tlf::end() const
Inicializa un iterator al final de la guia.
ostream& operator<<(ostream &os, Guia_Tlf &g)
Escritura de la guia de telefonos.
os flujo de salida. Es MODIFICADO g guia de telefonos que se escribe el flujo de salida
istream& operator>>(istream &is, Guia_Tlf &g)
Lectura de la guia de telefonos.
is flujo de entrada. ES MODIFICADO g guia de telefonos. ES MODIFICADO el flujo de entrada