imagenES.h
TipoImagen
TipoImagen LeerTipoImagen(const char *nombre)
Devuelve el tipo de imagen del archivo.
nombre indica el archivo de disco que consultar Devuelve el tipo de la imagen en el archivo TipoImagen Devuelve el tipo de imagen del archivo. nombre a leer el tipo imagen TipoImagen leido
References LeerTipo.
Referenced by Imagen::CargarImagen.
unsigned char* LeerImagenPPM(const char *nombre, int &fils, int &cols)
Lee una imagen de tipo PPM.
nombre archivo a leer fils filas Parámetro de salida con las filas de la imagen. cols columnas Parámetro de salida con las columnas de la imagen. puntero a una nueva zona de memoria que contiene filas x columnas x 3 bytes que corresponden a los colores de todos los píxeles en formato RGB (desde la esquina superior izqda a la inferior drcha). En caso de que no no se pueda leer, se devuelve cero. (0). En caso de éxito, el puntero apunta a una zona de memoria reservada en memoria dinámica. Será el usuario el responsable de liberarla.
References LeerCabecera, LeerTipo.
Referenced by Imagen::CargarImagen.
bool EscribirImagenPPM(const char *nombre, const unsigned char *datos, const int fils, const int cols)
Escribe una imagen de tipo PPM.
nombre archivo a escribir datos punteros a los f x c x 3 bytes que corresponden a los valores de los píxeles de la imagen en formato RGB. fils filas de la imagen cols columnas de la imagen si ha tenido éxito en la escritura.
unsigned char* LeerImagenPGM(const char *nombre, int &fils, int &cols)
Lee una imagen de tipo PGM.
nombre archivo a leer fils filas Parámetro de salida con las filas de la imagen. cols columnas Parámetro de salida con las columnas de la imagen. puntero a una nueva zona de memoria que contiene filas x columnas bytes que corresponden a los grises de todos los píxeles (desde la esquina superior izqda a la inferior drcha). En caso de que no no se pueda leer, se devuelve cero. (0). En caso de éxito, el puntero apunta a una zona de memoria reservada en memoria dinámica. Será el usuario el responsable de liberarla.
References LeerCabecera, LeerTipo.
Referenced by Imagen::CargarImagen.
bool EscribirImagenPGM(const char *nombre, const unsigned char *datos, const int fils, const int cols)
Escribe una imagen de tipo PGM.
nombre archivo a escribir datos punteros a los f x c bytes que corresponden a los valores de los píxeles de la imagen de grises. fils f filas de la imagen cols c columnas de la imagen si ha tenido éxito en la escritura.
Referenced by Imagen::GuardarImagen.