main_imagen.cpp
void CifrarMensaje(Imagen &I)
funcion que cifra un mensaje dentro de una imagen
I imagen donde cifraremos el mensaje f y c deben ser mayores que 0 I es modificado para alojar el mensaje
References Imagen::asigna_pixel, Imagen::consultar_pixel, Imagen::num_columnas, Imagen::num_filas.
Referenced by negativo.
bool LeerMensajeCifrado(const Imagen &I, string &cadena)
funcion que lee un mensaje cifrado en la imagen I
I imagen donde buscaremos el mensaje cadena string donde guardaremos el mensaje leido f y c deben ser mayores que 0 Devuelve true si se ha leido un mensaje oculto, false en caso contrario
References Imagen::consultar_pixel, Imagen::num_columnas, Imagen::num_filas.
Referenced by negativo.
void AumentarContraste(Imagen &I, int min, int max)
funcion aumenta el contraste en la imagen I
I imagen a modificar min minimo valor de gris para la imagen resultante max maximo valor de gris para la imagen resultante f y c deben ser mayores que 0 pixeles de I modificados
References Imagen::asigna_pixel, Imagen::consultar_pixel, Imagen::num_columnas, Imagen::num_filas.
Referenced by negativo.
void umbralizar_escala_grises(Imagen &I, int t1, int t2)
funcion que umbraliza la imagen I por valores dados
I imagen a modificar t1 rango minimo del umbral t2 rango maximo del umbral f y c deben ser mayores que 0 pixeles de I modificados
References Imagen::asigna_pixel, Imagen::consultar_pixel, Imagen::num_columnas, Imagen::num_filas.
Referenced by negativo.
void umbralizar_automatico(Imagen &I, int e)
funcion que umbraliza automaticamente una imagen I
I imagen a modificar e valor pequeño que condiciona el umbral calculado f y c deben ser mayores que 0 pixeles de I modificados
References Imagen::asigna_pixel, Imagen::consultar_pixel, Imagen::num_columnas, Imagen::num_filas.
Referenced by negativo.
void zoom(Imagen &I, pair< int, int > ei, int dim)
funcion que hace un zoom en una imagen I a partir de la esquina superior izquierda de la imagen y las dimensiones del zoom a hacer
I imagen a modificar ei par de coordenadas que determinan la esquina superior izquierda de la nueva imagen en la imagen actual. dim dimension dimXdim del zoom a realizar f y c deben ser mayores que 0 pixeles de I modificados
References Imagen::asigna_pixel, Imagen::consultar_pixel, Imagen::num_columnas, Imagen::num_filas.
Referenced by negativo.
void enmarca_imagen(Imagen &I)
funcion que crea un marco negro a una imagen
I imagen a modificar f y c deben ser mayores que 0 marco negro creado en la Imagen I
References Imagen::asigna_pixel, Imagen::num_columnas, Imagen::num_filas.
Referenced by negativo.
void Icono_Imagen(Imagen &I)
funcion que crea un icono dada una Imagen I a partir del numero de veces que sea desea reducir la imagen.
I imagen a modificar f y c deben ser mayores que 0 La imagen I es encogida
References Imagen::asigna_pixel, Imagen::consultar_pixel, Imagen::num_columnas, Imagen::num_filas.
Referenced by negativo.
void negativo(Imagen &I)
funcion que el negativo de una Imagen
I imagen a modificar f y c deben ser mayores que 0 La imagen I es encogida
References Imagen::asigna_pixel, AumentarContraste, Imagen::CargarImagen, CifrarMensaje, Imagen::consultar_pixel, enmarca_imagen, Imagen::GuardarImagen, Icono_Imagen, LeerMensajeCifrado, Imagen::num_columnas, Imagen::num_filas, umbralizar_automatico, umbralizar_escala_grises, zoom.
int main(int argc, char *argv[])