.TH "Guia_Tlf::const_iterator" 3 "Sábado, 12 de Diciembre de 2020" "guiatlf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Guia_Tlf::const_iterator \- 
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBconst_iterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBconst_iterator\fP & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "const pair< const string, list< string > > & \fBoperator*\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBconst_iterator\fP &i)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBconst_iterator\fP &i)"
.br
.ti -1c
.RI "\fBconst_iterator\fP & \fBoperator=\fP (const \fBconst_iterator\fP &i)"
.br
.ti -1c
.RI "\fBconst_iterator\fP & \fBoperator+\fP (int a)"
.br
.in -1c
.SS "Amigas"

.in +1c
.ti -1c
.RI "class \fBGuia_Tlf\fP"
.br
.in -1c

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para guiatlf del código fuente\&.
