.TH "repGuia_Tlf" 3 "Sábado, 12 de Diciembre de 2020" "guiatlf" \" -*- nroff -*-
.ad l
.nh
.SH NAME
repGuia_Tlf \- Rep del TDA \fBGuia_Tlf\fP 

.SH "Invariante de la representación"
.PP
El invariante es \fIpara\fP todo \fIi\fP y \fIj\fP tal que i<j entonces \fIe1i\fP y e1j son distintos
.SH "Función de abstracción"
.PP
Un objeto válido \fIrep\fP del TDA \fBGuia_Tlf\fP representa al valor
.PP
{(rep\&.begin()\&.first,rep\&.begin()\&.second),(rep\&.begin()+1\&.first,rep\&.begin()+1\&.second),\&.\&.\&.\&.,(rep\&.begin()+n-1\&.first,rep\&.begin()+n-1\&.second)} 
