.TH "Referencia del directorio include" 3 "Viernes, 13 de Noviembre de 2020" "cola_max" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio include \- 
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBcola_max\&.h\fP"
.br
.RI "\fIFichero cabecera del TDA \fBcola_max\fP\&. \fP"
.ti -1c
.RI "archivo \fBelemento\&.h\fP"
.br
.RI "\fIfichero de la estructura de datos elemento\&. ele es el valor asignado a elemento y max_ele es el valor máximo añadido hasta ahora \fP"
.in -1c
