.TH "Referencia del directorio src" 3 "Viernes, 13 de Noviembre de 2020" "cola_max" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio src \- 
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBcola\&.cpp\fP"
.br
.RI "\fIImplementación del TDA Cola\&. \fP"
.ti -1c
.RI "archivo \fBcola_max\&.cpp\fP"
.br
.RI "\fIfichero que implementa el TDA \fBcola_max\fP \fP"
.ti -1c
.RI "archivo \fBuso_cola_max\&.cpp\fP"
.br
.RI "\fIfichero que hace uso del TDA \fBcola_max\fP\&. crea una cola, le inserta 10 elementos, los saca e imprime por pantalla\&. \fP"
.in -1c
