.TH "src/cola.cpp" 3 "Viernes, 13 de Noviembre de 2020" "cola_max" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/cola.cpp \- ImplementaciÛn del TDA Cola\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cassert>\fP
.br

.SH "Descripci√≥n detallada"
.PP 
ImplementaciÛn del TDA Cola\&. 


.SH "Autor"
.PP 
Generado autom√°ticamente por Doxygen para cola_max del c√≥digo fuente\&.
