.TH "src/cola_max.cpp" 3 "Viernes, 13 de Noviembre de 2020" "cola_max" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/cola_max.cpp \- fichero que implementa el TDA \fBcola_max\fP  

.SH SYNOPSIS
.br
.PP
\fC#include 'cola_max\&.h'\fP
.br

.SH "Descripción detallada"
.PP 
fichero que implementa el TDA \fBcola_max\fP 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para cola_max del código fuente\&.
