.TH "include/elemento.h" 3 "Viernes, 13 de Noviembre de 2020" "cola_max" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/elemento.h \- fichero de la estructura de datos elemento\&. ele es el valor asignado a elemento y max_ele es el valor máximo añadido hasta ahora  

.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "struct \fBelemento\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
fichero de la estructura de datos elemento\&. ele es el valor asignado a elemento y max_ele es el valor máximo añadido hasta ahora 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para cola_max del código fuente\&.
