.TH "imagen.cpp" 3 "Lunes, 2 de Noviembre de 2020" "tdaimagen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
imagen.cpp \- Fichero con definiciones de los metodos de la clase imagen\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'imagen\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br

.SH "Descripción detallada"
.PP 
Fichero con definiciones de los metodos de la clase imagen\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para tdaimagen del código fuente\&.
