.TH "imagen.h" 3 "Lunes, 2 de Noviembre de 2020" "tdaimagen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
imagen.h \- Fichero cabecera del TDA \fBImagen\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'imagenES\&.h'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBImagen\fP"
.br
.RI "\fIT\&.D\&.A\&. \fBImagen\fP\&. \fP"
.in -1c
.SS "'typedefs'"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBbyte\fP"
.br
.RI "\fIbyte tipo de dato a tratar en los pixeles \fP"
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA \fBImagen\fP\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para tdaimagen del código fuente\&.
