.TH "Referencia del directorio include" 3 "Sábado, 12 de Diciembre de 2020" "diccionario" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio include \- 
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBdiccionario\&.h\fP"
.br
.RI "\fIfichero que implementa el TDA diccionario \fP"
.in -1c
