.TH "Referencia del directorio src" 3 "Sábado, 12 de Diciembre de 2020" "diccionario" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio src \- 
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBusodiccionario\&.cpp\fP"
.br
.RI "\fIfichero para probar el TDA diccionario \fP"
.in -1c
