.TH "data< T, U >" 3 "Sábado, 12 de Diciembre de 2020" "diccionario" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data< T, U > \- 
.SH SYNOPSIS
.br
.PP
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "T \fBclave\fP"
.br
.ti -1c
.RI "list< U > \fBinfo_asoci\fP"
.br
.in -1c

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para diccionario del código fuente\&.
