.TH "Diccionario< T, U >::const_iterator" 3 "Sábado, 12 de Diciembre de 2020" "diccionario" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Diccionario< T, U >::const_iterator \- 
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBconst_iterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBconst_iterator\fP & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "const \fBdata\fP< T, U > & \fBoperator*\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBconst_iterator\fP &i) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBconst_iterator\fP &i) const "
.br
.in -1c
.SS "Amigas"

.in +1c
.ti -1c
.RI "class \fBDiccionario\fP"
.br
.in -1c

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para diccionario del código fuente\&.
