.TH "include/diccionario.h" 3 "Sábado, 12 de Diciembre de 2020" "diccionario" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/diccionario.h \- fichero que implementa el TDA diccionario  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <list>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "struct \fBdata< T, U >\fP"
.br
.ti -1c
.RI "class \fBDiccionario< T, U >\fP"
.br
.ti -1c
.RI "class \fBDiccionario< T, U >::iterator\fP"
.br
.ti -1c
.RI "class \fBDiccionario< T, U >::const_iterator\fP"
.br
.in -1c
.SS "Funciones"

.in +1c
.ti -1c
.RI "template<class T , class U > bool \fBoperator<\fP (const \fBdata\fP< T, U > &d1, const \fBdata\fP< T, U > &d2)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
fichero que implementa el TDA diccionario 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para diccionario del código fuente\&.
