.TH "src/usodiccionario.cpp" 3 "Sábado, 12 de Diciembre de 2020" "diccionario" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/usodiccionario.cpp \- fichero para probar el TDA diccionario  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'diccionario\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBDiccionario\fP< string, string > &D)"
.br
.ti -1c
.RI "istream & \fBoperator>>\fP (istream &is, \fBDiccionario\fP< string, string > &D)"
.br
.ti -1c
.RI "void \fBEscribeSigni\fP (const list< string > &l)"
.br
.ti -1c
.RI "void \fBImprimeAlReves\fP (const \fBDiccionario\fP< string, string > &D)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Descripción detallada"
.PP 
fichero para probar el TDA diccionario 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para diccionario del código fuente\&.
