.TH "Referencia del directorio src" 3 "Viernes, 13 de Noviembre de 2020" "pila_max" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio src \- 
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBpila_max\&.cpp\fP"
.br
.RI "\fIfichero que decide que contenedor se usará para representar una pila (un vector o una cola)\&. \fP"
.ti -1c
.RI "archivo \fBpila_max_cola\&.cpp\fP"
.br
.RI "\fIFichero donde se implementa el TDA pila_max_cola\&. \fP"
.ti -1c
.RI "archivo \fBpila_max_vd\&.cpp\fP"
.br
.RI "\fIFichero que implementa el TDA pila_max_vd\&. \fP"
.ti -1c
.RI "archivo \fBuso_pila_max\&.cpp\fP"
.br
.RI "\fIfichero que testea el TDA pila_max \fP"
.in -1c
