.TH "Referencia del directorio include" 3 "Viernes, 13 de Noviembre de 2020" "pila_max" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio include \- 
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBcola\&.h\fP"
.br
.RI "\fIFichero cabecera del TDA \fBCola\fP\&. \fP"
.ti -1c
.RI "archivo \fBpila_max\&.h\fP"
.br
.RI "\fIfichero que define que contenedor se usará para representar una pila (un vector o una cola)\&. \fP"
.ti -1c
.RI "archivo \fBpila_max_cola\&.h\fP"
.br
.RI "\fIFichero cabecera del TDA pila_max_cola\&. \fP"
.ti -1c
.RI "archivo \fBpila_max_vd\&.h\fP"
.br
.RI "\fIFichero cabecera del TDA pila_max_vd\&. \fP"
.in -1c
