.TH "src/cola.cpp" 3 "Lunes, 9 de Noviembre de 2020" "pila_max" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/cola.cpp \- ImplementaciÛn del TDA \fBCola\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cassert>\fP
.br

.SH "Descripci√≥n detallada"
.PP 
ImplementaciÛn del TDA \fBCola\fP\&. 


.SH "Autor"
.PP 
Generado autom√°ticamente por Doxygen para pila_max del c√≥digo fuente\&.
