.TH "elemento" 3 "Viernes, 13 de Noviembre de 2020" "pila_max" \" -*- nroff -*-
.ad l
.nh
.SH NAME
elemento \- 
.SH SYNOPSIS
.br
.PP
.SS "Atributos públicos"

.in +1c
.ti -1c
.RI "int \fBele\fP"
.br
.ti -1c
.RI "int \fBmax_ele\fP"
.br
.in -1c

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para pila_max del código fuente\&.
