.TH "Pila_max" 3 "Viernes, 13 de Noviembre de 2020" "pila_max" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pila_max \- 
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "const \fBelemento\fP \fBtope\fP ()"
.br
.RI "\fIMétodo que devuelve el tope de la pila\&. \fP"
.ti -1c
.RI "void \fBquitar\fP ()"
.br
.RI "\fIMétodo que quita el elemento del tope de la pila (igual que pop()) \fP"
.ti -1c
.RI "void \fBponer\fP (int e)"
.br
.RI "\fIMétodo que añade un elemento con valor e por el tope de la pila\&. \fP"
.ti -1c
.RI "bool \fBvacia\fP () const "
.br
.ti -1c
.RI "int \fBsize\fP () const "
.br
.RI "\fIMétodo que devuelve el tamaño de la pila\&. \fP"
.ti -1c
.RI "\fBelemento\fP \fBtope\fP () const "
.br
.RI "\fIMétodo que devuelve el tope de la pila\&. \fP"
.ti -1c
.RI "void \fBquitar\fP ()"
.br
.RI "\fIMétodo que quita el elemento del tope de la pila (igual que pop()) \fP"
.ti -1c
.RI "void \fBponer\fP (int e)"
.br
.RI "\fIMétodo que añade un elemento con valor e por el tope de la pila\&. \fP"
.ti -1c
.RI "bool \fBvacia\fP () const "
.br
.ti -1c
.RI "int \fBsize\fP () const "
.br
.RI "\fIMétodo que devuelve el tamaño de la pila\&. \fP"
.in -1c
.SH "Documentación de las funciones miembro"
.PP 
.SS "void Pila_max::poner (int e)"

.PP
Método que añade un elemento con valor e por el tope de la pila\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIe\fP valor que tendrá el elemento a añadir 
.RE
.PP

.SS "void Pila_max::poner (int e)"

.PP
Método que añade un elemento con valor e por el tope de la pila\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIe\fP valor que tendrá el elemento a añadir 
.RE
.PP

.PP
Hace referencia a Cola< T >::poner(), tope() y Cola< T >::vacia()\&.
.PP
Referenciado por tope()\&.
.SS "int Pila_max::size () const"

.PP
Método que devuelve el tamaño de la pila\&. 
.PP
\fBDevuelve:\fP
.RS 4
número de elementos de la pila 
.RE
.PP

.SS "int Pila_max::size () const"

.PP
Método que devuelve el tamaño de la pila\&. 
.PP
\fBDevuelve:\fP
.RS 4
número de elementos de la pila 
.RE
.PP

.PP
Hace referencia a Cola< T >::num_elementos()\&.
.PP
Referenciado por tope()\&.
.SS "\fBelemento\fP Pila_max::tope () const"

.PP
Método que devuelve el tope de la pila\&. 
.PP
\fBDevuelve:\fP
.RS 4
elemento objeto elemento tope de la pila 
.RE
.PP

.PP
Hace referencia a poner(), quitar(), size() y tope()\&.
.SS "const \fBelemento\fP Pila_max::tope ()"

.PP
Método que devuelve el tope de la pila\&. 
.PP
\fBDevuelve:\fP
.RS 4
elemento objeto elemento tope de la pila 
.RE
.PP

.PP
Hace referencia a Cola< T >::frente(), Cola< T >::quitar() y size()\&.
.PP
Referenciado por poner() y tope()\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para pila_max del código fuente\&.
