.TH "include/pila_max_vd.h" 3 "Viernes, 13 de Noviembre de 2020" "pila_max" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/pila_max_vd.h \- Fichero cabecera del TDA pila_max_vd\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'elemento\&.h'\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBPila_max\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA pila_max_vd\&. 

Gestiona una secuencia de elementos con facilidades para la inserción y borrado de elementos en un extremo 
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para pila_max del código fuente\&.
