.TH "include/pila_max.h" 3 "Viernes, 13 de Noviembre de 2020" "pila_max" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/pila_max.h \- fichero que define que contenedor se usará para representar una pila (un vector o una cola)\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pila_max_vd\&.h'\fP
.br

.SS "'defines'"

.in +1c
.ti -1c
.RI "#define \fBCUAL_COMPILA\fP   1"
.br
.in -1c
.SH "Descripción detallada"
.PP 
fichero que define que contenedor se usará para representar una pila (un vector o una cola)\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para pila_max del código fuente\&.
