.TH "src/uso_pila_max.cpp" 3 "Viernes, 13 de Noviembre de 2020" "pila_max" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/uso_pila_max.cpp \- fichero que testea el TDA pila_max  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'pila_max\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &o, const \fBelemento\fP &e)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Descripción detallada"
.PP 
fichero que testea el TDA pila_max 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para pila_max del código fuente\&.
