cola_max
stack<elemento> cola_max::mipila1
const elemento cola_max::front()
Método que devuelve el primer elemento de la cola.
objeto constante de tipo elemento
const elemento cola_max::back()
Método que devuelve el último elemento de la cola.
objeto constante de tipo elemento
Referenced by operator<<.
void cola_max::quitar()
Método que quita el último elemento de la cola.
Referenced by operator<<.
void cola_max::poner(int e)
Método que añade un elemento con valor e al principio de la cola.
References vacia.
Referenced by operator<<.
bool cola_max::vacia() const
Método que comprueba si la cola está vacía.
true si está vacía, de lo contrario false
Referenced by operator<<, poner.
int cola_max::size() const
Método que devuelve el número de elementos de la cola.
número de elementos de la cola