Pila_max
Cola<elemento> Pila_max::mipila
vector<elemento> Pila_max::mipila
const elemento Pila_max::tope()
Método que devuelve el tope de la pila.
elemento objeto elemento tope de la pila
References Cola< T >::frente, Cola< T >::quitar, size.
Referenced by poner, tope.
void Pila_max::quitar()
Método que quita el elemento del tope de la pila (igual que pop())
References Cola< T >::num_elementos, Cola< T >::poner, Cola< T >::frente, Cola< T >::quitar.
Referenced by tope.
void Pila_max::poner(int e)
Método que añade un elemento con valor e por el tope de la pila.
e valor que tendrá el elemento a añadir
References Cola< T >::poner, tope, Cola< T >::vacia.
Referenced by tope.
bool Pila_max::vacia() const
int Pila_max::size() const
Método que devuelve el tamaño de la pila.
número de elementos de la pila
References Cola< T >::num_elementos.
Referenced by tope.
elemento Pila_max::tope() const
Método que devuelve el tope de la pila.
elemento objeto elemento tope de la pila
References poner, quitar, size, tope.
void Pila_max::quitar()
Método que quita el elemento del tope de la pila (igual que pop())
void Pila_max::poner(int e)
Método que añade un elemento con valor e por el tope de la pila.
e valor que tendrá el elemento a añadir
bool Pila_max::vacia() const
int Pila_max::size() const
Método que devuelve el tamaño de la pila.
número de elementos de la pila