Cola
Celda* Cola< T >::primera
Puntero al primer nodo de la lista.
Celda* Cola< T >::ultima
Puntero al último nodo de la lista.
int Cola< T >::num_elem
Número de elementos de la cola.
Cola< T >::Cola()
Constructor por defecto.
Referenced by Cola< elemento >::Cola.
Cola< T >::Cola(const Cola< T > &original)
Constructor de copias.
original La cola de la que se hará la copia.
Cola< T >::~Cola()
Destructor.
Referenced by Cola< elemento >::Cola.
Cola< T > & Cola< T >::operator=(const Cola< T > &otra)
Operador de asignación
otra La cola que se va a asignar.
Referenced by Cola< elemento >::Cola.
bool Cola< T >::vacia() const
Comprueba si la cola está vacía
Referenced by Pila_max::poner.
T& Cola< T >::frente()
Devuelve el elemento del frente de la cola.
Referenced by Pila_max::tope, Pila_max::quitar.
const T& Cola< T >::frente() const
Devuelve el elemento del frente de una cola constante.
void Cola< T >::poner(const T &elem)
Añade un elemento al final de la cola.
elem Elemento que se va a añadir.
Referenced by Cola< elemento >::frente, Pila_max::poner, Pila_max::quitar.
void Cola< T >::quitar()
Quita el elemento del frente de la cola.
Referenced by Cola< elemento >::frente, Pila_max::tope, Pila_max::quitar.
int Cola< T >::num_elementos() const
Devuelve el número de elementos de la cola.
Referenced by Pila_max::quitar, Pila_max::size.